# =============================================================================
# 游깷 MOTOR H칈BRIDO DE CONECTIVIDAD: WIFI + IMPROV BLE + AP RESCATE
# =============================================================================
# Descripci칩n: 
#   Gestiona inteligentemente la conexi칩n del dispositivo. Inicialmente levanta 
#   Bluetooth Low Energy (Improv) para que el due침o pase la clave del WiFi por
#   la app de Home Assistant. Si ya tiene clave pero pierde el WiFi, espera 15 min 
#   y levanta una red abierta de rescate (Modo AP) para reconfiguraci칩n manual.
# =============================================================================

# -----------------------------------------------------------------------------
# CONSTANTES DE RED (Puedes modificar estos comportamientos si lo necesitas)
# -----------------------------------------------------------------------------
substitutions:
  # -> CONFIGURA AQU칈: Claves de emergencia
  ap_password: "0123456789"         # Clave de la red WiFi emitida por el dispositivo si fracasa todo
  web_server_password: "0123456789" # Clave del portal web local (El usuario siempre es: admin)
  
  # -> CONFIGURA AQU칈: Tiempos de reacci칩n (Cuidado: valores muy agresivos colapsan la placa)
  intervalo_chequeo: 15s        # Cada cu치ntos segundos el Cerebro revisa si sigue conectado a internet
  umbral_reiniciar_api: "240"   # N칰mero de chequeos perdidos para reiniciar: 240 x 15s = 1 hora (3600s)

# -----------------------------------------------------------------------------
# MOTOR PRINCIPAL WIFI
# -----------------------------------------------------------------------------
wifi:
  id: componente_wifi
  # enable_on_boot DEBE estar habilitado impl칤citamente, Improv BLE USA el chip WiFi de fondo
  power_save_mode: none     # Mejora radicalmente la velocidad de respuesta apagando el ahorro energ칠tico de antena
  reboot_timeout: 0s        # EVITA reinicios nativos ciegos, nuestro script de la l칤nea 143 se encarga de esto con cabeza.
  output_power: 20dBm       # Potencia de emisi칩n m치xima (Cuidado en zonas muy saturadas)
  
  # Red de emergencia (Fallback AP). Se enciende DENTRO del script de la l칤nea 176 tras 15 minutos sin WiFi
  ap:
    password: "${ap_password}"
    # ap_timeout desactivado deliberadamente. El chip de una ESP32-C3 entra en p치nico 
    # si intenta emitir Improv Bluetooth y un Access Point WiFi por la misma antena a la vez.
    
    # Rango IP de estabilidad (Tu m칩vil recibir치 una IP 192.168.4.x para ajustar la placa)
    manual_ip:
      static_ip: 192.168.4.1
      gateway: 192.168.4.1
      subnet: 255.255.255.0

# -----------------------------------------------------------------------------
# PORTALES DE CONFIGURACI칍N INICIAL DEL USUARIO
# -----------------------------------------------------------------------------

# 1. Improv por Bluetooth (Solo para placa Virgen, se duerme cuando consigue WiFi)
esp32_ble:
esp32_improv:
  status_indicator: led_estado_sistema
  authorizer: none        # Sin bot칩n f칤sico requerido, emparejamiento libre pero cercano
  wifi_timeout: 5s        # Inicia Improv super r치pido apenas se da cuenta de que no hay WiFi base configurado
  next_url: "https://my.home-assistant.io/redirect/config_flow_start?domain=esphome"
  
  on_start:
    then:
      - logger.log: "Improv BLE: Esperando App M칩vil o PC"
  on_provisioning:
    then:
      - logger.log: "Improv BLE: Recibiendo credenciales e inyect치ndolas en NVS Flash..."
  on_provisioned:
    then:
      - logger.log: "Improv BLE: 춰칄xito cruzando el apret칩n de manos!"
      - lambda: |-
          id(wifi_provisioned) = true; // Graba a fuego que la placa ya no es virgen
      - homeassistant.service:
          service: notify.persistent_notification
          data:
            title: "游릭 Dispositivo Conectado a la Red"
            message: "El hardware se provision칩 correctamente v칤a BLE Improv."
  on_stop:
    then:
      - logger.log: "Improv BLE: detenido permanentemente"

  # Telemetr칤a Avanzada: Loggea cada vez que cambia el estado interno o hay un error
  on_state:
    then:
      - lambda: |-
          // Loggear el estado principal del motor
          switch (state) {
            case improv::STATE_STOPPED:
              ESP_LOGD("improv", "Estado C++: STATE_STOPPED (Motor Detenido)"); break;
            case improv::STATE_PROVISIONING:
              ESP_LOGD("improv", "Estado C++: STATE_PROVISIONING (Recibiendo datos de red...)"); break;
            case improv::STATE_PROVISIONED:
              ESP_LOGD("improv", "Estado C++: STATE_PROVISIONED (춰Conexi칩n Exitosa!)"); break;
          }
          
          // Loggear si HA detect칩 alg칰n error al pasar la clave
          if (error != improv::ERROR_NONE) {
            switch(error) {
              case improv::ERROR_UNABLE_TO_CONNECT:
                ESP_LOGE("improv", "Error BLE: No ha podido conectar al WiFi (Clave incorrecta / Lejos del router)"); break;
              case improv::ERROR_NOT_AUTHORIZED:
                ESP_LOGE("improv", "Error BLE: El dispositivo cliente no est치 autorizado"); break;
              default:
                ESP_LOGE("improv", "Error BLE Desconocido o RPC Inv치lido (C칩digo: %d)", error); break;
            }
          }

# Improv por Serial (configuraci칩n WiFi por USB)
# improv_serial:
  # next_url: "https://my.home-assistant.io/redirect/config_flow_start?domain=esphome"

# Web Server (Panel local de recuperaci칩n / OTA local)
web_server:
  port: 80
  auth:
    username: "admin"
    password: "${web_server_password}"

# -----------------------------------------------------------------------------
# MOTOR DE MONITOREO CONSTANTE
# -----------------------------------------------------------------------------
interval:
  - interval: ${intervalo_chequeo}
    then:
      - script.execute: chequeo_estado

globals:
  - id: wifi_provisioned
    type: bool
    restore_value: true   # Se guarda en flash NVS
    initial_value: 'false'
  # --- Estados booleanos solicitados ---
  - id: estado_wifi_activo
    type: bool
    restore_value: false
    initial_value: "false"
  - id: estado_api_activa
    type: bool
    restore_value: false
    initial_value: "false"
  - id: estado_ap_activo
    type: bool
    restore_value: false
    initial_value: "false"

  # --- Contadores de fallos ---
  - id: tiempo_sin_wifi_seg
    type: int
    restore_value: false
    initial_value: "0"
  - id: intentos_sin_api
    type: int
    restore_value: false
    initial_value: "0"

script:
  - id: chequeo_estado
    mode: single
    then:
      # ========================================================
      # 1. ACTUALIZAR GLOBALES BOOLEANAS
      # ========================================================
      - if:
          condition: wifi.connected
          then:
            - lambda: "id(estado_wifi_activo) = true;"
          else:
            - lambda: "id(estado_wifi_activo) = false;"
      - if:
          condition:
            lambda: "return id(componente_wifi).is_ap_active();"
          then:
            - lambda: "id(estado_ap_activo) = true;"
          else:
            - lambda: "id(estado_ap_activo) = false;"

      - if:
          condition: api.connected
          then:
            - lambda: "id(estado_api_activa) = true;"
          else:
            - lambda: "id(estado_api_activa) = false;"


      # ========================================================
      # 2. L칍GICA DE RECUPERACI칍N CONDICIONAL (AP & API)
      # ========================================================

      # --- L칩gica AP Fallback Inteligente (cada 15min) ---
      - if:
          condition:
            - not: wifi.connected
            - lambda: "return id(wifi_provisioned);"
          then:
            - lambda: "id(tiempo_sin_wifi_seg) += 15;"
            # Encender AP a los 15 minutos exactos de caerse el wifi
            - if:
                condition:
                  lambda: "return id(tiempo_sin_wifi_seg) == 900;"
                then:
                  - logger.log: "15 min sin WiFi principal. Activando Modo AP de rescate."
                  - wifi.ap.enable:
            # Reintentar conectarse al router cada 15 min estando en AP
            - if:
                condition:
                  lambda: "return id(tiempo_sin_wifi_seg) >= 1800;"
                then:
                  - logger.log: "Ciclo de 15 min en Modo AP cumplido. Apagando red temporal e intentando reconectar al WiFi de casa..."
                  - wifi.ap.disable:
                  - wifi.disable:
                  - delay: 2s
                  - wifi.enable:
                  - lambda: "id(tiempo_sin_wifi_seg) = 0;" # Resetea el reloj a 0 para el siguiente intento
          else:
            - lambda: "id(tiempo_sin_wifi_seg) = 0;"
            # Si el WiFi vuelve (o si estamos en primer arranque virgen Improv), asegurar que el AP este apagado
            - if:
                condition:
                  lambda: "return id(componente_wifi).is_ap_active();"
                then:
                  - wifi.ap.disable:

      # --- Fallo de API (con WiFi activo) ---
      - if:
          condition: wifi.connected
          then:
            - if:
                condition: api.connected
                then:
                  - lambda: "id(intentos_sin_api) = 0;"
                else:
                  - lambda: "id(intentos_sin_api)++;"
                  - if:
                      condition: 
                        lambda: "return id(intentos_sin_api) >= ${umbral_reiniciar_api};"
                      then:
                        - logger.log: "API sin conexi칩n (>= ${umbral_reiniciar_api} intentos). Reiniciando el dispositivo."
                        - button.press: boton_reinicio

# -----------------------------------------------------------------------------
# HERRAMIENTAS DE RED (BOTONES EN HOME ASSISTANT)
# -----------------------------------------------------------------------------
button:
  - platform: template
    name: "Reconectar WiFi"
    icon: "mdi:wifi-refresh"
    on_press:
      then:
        # Forzar desconexi칩n limpia y reconexi칩n
        - wifi.disable:
        - delay: 2s
        - wifi.enable:

# -----------------------------------------------------------------------------
# SALIDAS DE HARDWARE (OUTPUTS)
# -----------------------------------------------------------------------------
output:
  # Salida gen칠rica para controlar el LED integrado de la placa seg칰n el perfil
  - platform: gpio
    id: led_estado_sistema
    internal: true
    pin:
      number: ${pin_led_estado}
      inverted: ${pin_led_invertido}
      ignore_strapping_warning: true
