# lib-wifi_conectividad.yaml
# Uso: packages: wifi: !include lib/lib-wifi_conectividad.yaml
# Requiere: friendly_name; secrets: admin
#
# Incluye: Motor de red h칤brido (WiFi, Modo AP fallback, Improv BLE, Improv Serial, Web Server)
# y telemetr칤a de monitoreo continuo de conexi칩n.

# --- Constantes (editar aqu칤 para cambiar valores por defecto del sistema) ---
substitutions:
  # Contrase침a para la red WiFi de emergencia (Fallback AP)
  ap_password: "0123456789"
  # Contrase침a para la interfaz web local de rescate (usuario: admin)
  web_server_password: "0123456789"
  intervalo_chequeo: 15s # Frecuencia de chequeo del estado de red
  tiempo_activar_ap: "3min"  # Tiempo sin WiFi antes de levantar la antena local de rescate (Nativo de ESPHome)
  umbral_reiniciar_api: "20" # 20 chequeos de 15s = 5 minutos sin Home Assistant para forzar un reinicio

# -----------------------------------------------------------------------------
# MOTOR PRINCIPAL WIFI
# -----------------------------------------------------------------------------
wifi:
  id: componente_wifi
  # enable_on_boot: false  <- ELIMINADO: Improv BLE necesita que el radio WiFi est칠 encendido para escanear redes.
  power_save_mode: none
  # fast_connect: true (Desactivado al no tener redes pre-configuradas)
  reboot_timeout: 0s
  output_power: 20dBm
  
  # Red de emergencia (Fallback AP) si desaparecen las credenciales
  ap:
    password: "${ap_password}"
    ap_timeout: ${tiempo_activar_ap}
    # IP fija del AP para conexiones m치s estables (ajusta a tu red si hace falta)
    manual_ip:
      static_ip: 192.168.4.1
      gateway: 192.168.4.1
      subnet: 255.255.255.0

# -----------------------------------------------------------------------------
# PORTALES DE CONEXI칍N AL CONSUMIDOR (Improv & Web Server)
# -----------------------------------------------------------------------------
# Improv por Bluetooth (Solo ESP32 / ESP32-C3)
esp32_improv:
  status_indicator: led_estado_sistema
  authorizer: none
  wifi_timeout: 5s        # Sin espera: arranca Improv al instante si no hay WiFi
  next_url: "https://my.home-assistant.io/redirect/config_flow_start?domain=esphome"
  on_start:
    then:
      - logger.log: "Improv BLE: esperando autorizaci칩n / autorizado"
  on_provisioning:
    then:
      - logger.log: "Improv BLE: provisionando WiFi..."
  on_provisioned:
    then:
      - logger.log: "Improv BLE: WiFi configurado correctamente"
      - lambda: |-
          id(wifi_provisioned) = true;
      - homeassistant.service:
          service: notify.persistent_notification
          data:
            title: "游릭 Dispositivo provisionado"
            message: "El dispositivo se conect칩 al WiFi por primera vez via BLE Improv."
  on_stop:
    then:
      - logger.log: "Improv BLE: detenido"

# Improv por Serial (configuraci칩n WiFi por USB)
# improv_serial:
  # next_url: "https://my.home-assistant.io/redirect/config_flow_start?domain=esphome"

# Web Server (Panel local de recuperaci칩n / OTA local)
web_server:
  port: 80
  auth:
    username: "admin"
    password: "${web_server_password}"

# -----------------------------------------------------------------------------
# MOTOR DE MONITOREO CONSTANTE
# -----------------------------------------------------------------------------
interval:
  - interval: ${intervalo_chequeo}
    then:
      - script.execute: chequeo_estado

globals:
  - id: wifi_provisioned
    type: bool
    restore_value: true   # Se guarda en flash NVS
    initial_value: 'false'
  # --- Estados booleanos solicitados ---
  - id: estado_wifi_activo
    type: bool
    restore_value: false
    initial_value: "false"
  - id: estado_api_activa
    type: bool
    restore_value: false
    initial_value: "false"
  - id: estado_ap_activo
    type: bool
    restore_value: false
    initial_value: "false"

  # --- Contadores de fallos ---
  - id: intentos_sin_api
    type: int
    restore_value: false
    initial_value: "0"

script:
  - id: chequeo_estado
    mode: single
    then:
      # ========================================================
      # 1. ACTUALIZAR GLOBALES BOOLEANAS
      # ========================================================
      - if:
          condition: wifi.connected
          then:
            - lambda: "id(estado_wifi_activo) = true;"
          else:
            - lambda: "id(estado_wifi_activo) = false;"
      - if:
          condition:
            lambda: "return id(componente_wifi).is_ap_active();"
          then:
            - lambda: "id(estado_ap_activo) = true;"
          else:
            - lambda: "id(estado_ap_activo) = false;"

      - if:
          condition: api.connected
          then:
            - lambda: "id(estado_api_activa) = true;"
          else:
            - lambda: "id(estado_api_activa) = false;"


      # ========================================================
      # 2. L칍GICA DE RECUPERACI칍N (API ONLY, WiFi es Nativo)
      # ========================================================


      # --- Fallo de API (con WiFi activo) ---
      - if:
          condition: wifi.connected
          then:
            - if:
                condition: api.connected
                then:
                  - lambda: "id(intentos_sin_api) = 0;"
                else:
                  - lambda: "id(intentos_sin_api)++;"
                  - if:
                      condition: 
                        lambda: "return id(intentos_sin_api) >= ${umbral_reiniciar_api};"
                      then:
                        - logger.log: "API sin conexi칩n (>= ${umbral_reiniciar_api} intentos). Reiniciando el dispositivo."
                        - button.press: boton_reinicio

# -----------------------------------------------------------------------------
# HERRAMIENTAS DE RED (BOTONES EN HOME ASSISTANT)
# -----------------------------------------------------------------------------
button:
  - platform: template
    name: "${friendly_name} Reconectar WiFi"
    icon: "mdi:wifi-refresh"
    on_press:
      then:
        # Forzar desconexi칩n limpia y reconexi칩n
        - wifi.disable:
        - delay: 2s
        - wifi.enable:

# -----------------------------------------------------------------------------
# SALIDAS DE HARDWARE (OUTPUTS)
# -----------------------------------------------------------------------------
output:
  # Salida gen칠rica para controlar el LED integrado de la placa seg칰n el perfil
  - platform: gpio
    id: led_estado_sistema
    pin:
      number: ${pin_led_estado}
      inverted: ${pin_led_invertido}
      ignore_strapping_warning: true
