# lib-wifi_conectividad.yaml
# Uso: packages: wifi: !include lib-wifi_conectividad.yaml
# Requiere: friendly_name; secrets: wifi_ssid, wifi_password, ap_ssid, ap_password, admin
#
# Incluye: Motor de red h铆brido (WiFi, Modo AP fallback, Improv BLE, Improv Serial, Web Server)
# y telemetr铆a de monitoreo continuo de conexi贸n.

# --- Constantes (editar aqu铆 para cambiar valores por defecto del sistema) ---
substitutions:
  intervalo_chequeo: 15s # Frecuencia de chequeo del estado de red
  umbral_activar_ap: "6"   # 6 chequeos de 15s = 90 segundos sin WiFi para activar el Modo AP
  umbral_reiniciar_api: "20" # 20 chequeos de 15s = 5 minutos sin Home Assistant para forzar un reinicio

# -----------------------------------------------------------------------------
# MOTOR PRINCIPAL WIFI
# -----------------------------------------------------------------------------
wifi:
  power_save_mode: none
  fast_connect: true
  reboot_timeout: 0s
  output_power: 20dBm
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret ap_ssid
      password: !secret ap_password
  ap:
    password: !secret admin
    ap_timeout: 0s
    # IP fija del AP para conexiones m谩s estables (ajusta a tu red si hace falta)
    manual_ip:
      static_ip: 192.168.4.1
      gateway: 192.168.4.1
      subnet: 255.255.255.0

# -----------------------------------------------------------------------------
# PORTALES DE CONEXIN AL CONSUMIDOR (Improv & Web Server)
# -----------------------------------------------------------------------------
# Improv por Bluetooth (Solo ESP32 / ESP32-C3)
esp32_improv:
  authorizer: none
  wifi_timeout: 0s        # Sin espera: arranca Improv al instante si no hay WiFi
  next_url: "https://my.home-assistant.io/redirect/config_flow_start?domain=esphome"
  on_start:
    then:
      - logger.log: "Improv BLE: esperando autorizaci贸n / autorizado"
  on_provisioning:
    then:
      - logger.log: "Improv BLE: provisionando WiFi..."
  on_provisioned:
    then:
      - logger.log: "Improv BLE: WiFi configurado correctamente"
      - lambda: |-
          id(wifi_provisioned) = true;
      - homeassistant.service:
          service: notify.persistent_notification
          data:
            title: " Dispositivo provisionado"
            message: "El dispositivo se conect贸 al WiFi por primera vez via BLE Improv."
  on_stop:
    then:
      - logger.log: "Improv BLE: detenido"

# Improv por Serial (configuraci贸n WiFi por USB)
# improv_serial:
  # next_url: "https://my.home-assistant.io/redirect/config_flow_start?domain=esphome"

# Web Server (Panel local de recuperaci贸n / OTA local)
web_server:
  port: 80
  auth:
    username: "admin"
    password: !secret admin

# -----------------------------------------------------------------------------
# MOTOR DE MONITOREO CONSTANTE
# -----------------------------------------------------------------------------
interval:
  - interval: ${intervalo_chequeo}
    then:
      - script.execute: chequeo_estado

globals:
  - id: wifi_provisioned
    type: bool
    restore_value: true   # Se guarda en flash NVS
    initial_value: 'false'
  # --- Estados booleanos solicitados ---
  - id: estado_wifi_activo
    type: bool
    restore_value: false
    initial_value: "false"
  - id: estado_api_activa
    type: bool
    restore_value: false
    initial_value: "false"
  - id: estado_ap_activo
    type: bool
    restore_value: false
    initial_value: "false"

  # --- Contadores de fallos ---
  - id: intentos_sin_wifi
    type: int
    restore_value: false
    initial_value: "0"
  - id: intentos_sin_api
    type: int
    restore_value: false
    initial_value: "0"

script:
  - id: chequeo_estado
    mode: single
    then:
      # ========================================================
      # 1. ACTUALIZAR GLOBALES BOOLEANAS
      # ========================================================
      - if:
          condition: wifi.connected
          then:
            - lambda: "id(estado_wifi_activo) = true;"
          else:
            - lambda: "id(estado_wifi_activo) = false;"
      - if:
          condition: wifi.ap_active
          then:
            - lambda: "id(estado_ap_activo) = true;"
          else:
            - lambda: "id(estado_ap_activo) = false;"

      - if:
          condition: api.connected
          then:
            - lambda: "id(estado_api_activa) = true;"
          else:
            - lambda: "id(estado_api_activa) = false;"


      # ========================================================
      # 2. LGICA DE CONTADORES, SENSORES Y RECUPERACIN
      # ========================================================
      
      # --- Fallo de WiFi ---
      - if:
          condition:
            not:
              wifi.connected:
          then:
            - lambda: "id(intentos_sin_wifi)++;"
            - if:
                condition: lambda: "return id(intentos_sin_wifi) >= ${umbral_activar_ap};"
                then:
                  - wifi.enable_ap:
          else:
            - lambda: "id(intentos_sin_wifi) = 0;"


      # --- Fallo de API (con WiFi activo) ---
      - if:
          condition: wifi.connected
          then:
            - if:
                condition: api.connected
                then:
                  - lambda: "id(intentos_sin_api) = 0;"
                else:
                  - lambda: "id(intentos_sin_api)++;"
                  - if:
                      condition: lambda: "return id(intentos_sin_api) >= ${umbral_reiniciar_api};"
                      then:
                        - logger.log: "API sin conexi贸n (>= ${umbral_reiniciar_api} intentos). Reiniciando el dispositivo."
                        - restart

# -----------------------------------------------------------------------------
# HERRAMIENTAS DE RED (BOTONES EN HOME ASSISTANT)
# -----------------------------------------------------------------------------
button:
  - platform: template
    name: "${friendly_name} Forzar Modo AP"
    icon: "mdi:wifi-alert"
    on_press:
      then:
        - wifi.enable_ap:
  - platform: template
    name: "${friendly_name} Reconectar WiFi"
    icon: "mdi:wifi-refresh"
    on_press:
      then:
        # Forzar desconexi贸n limpia y reconexi贸n
        - wifi.disconnect:
        - delay: 2s
        - wifi.connect:
