# Plantilla sensores/botones para ESP8266
# Sin temperatura interna (solo ESP32) ni safe_mode; resto compatible

sensor:
  - platform: wifi_signal
    name: "${friendly_name} Señal WiFi"
    id: wifi_rssi
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"
    id: uptime_s
    unit_of_measurement: "s"
    accuracy_decimals: 0

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP"
    ssid:
      name: "${friendly_name} WiFi SSID"
    bssid:
      name: "${friendly_name} WiFi BSSID"
    mac_address:
      name: "${friendly_name} MAC"
  - platform: version
    name: "${friendly_name} Versión ESPHome"
    hide_timestamp: true

button:
  - platform: restart
    name: "${friendly_name} Reiniciar dispositivo"
  - platform: factory_reset
    name: "${friendly_name} Restablecer a fábrica"
  - platform: template
    name: "${friendly_name} Desconectar WiFi"
    icon: "mdi:wifi-off"
    on_press:
      then:
        - wifi.disconnect:
  - platform: template
    name: "${friendly_name} Reconectar WiFi"
    icon: "mdi:wifi-refresh"
    on_press:
      then:
        - wifi.reconnect:
  - platform: template
    name: "${friendly_name} Borrar credenciales WiFi"
    icon: "mdi:wifi-cancel"
    on_press:
      then:
        - lambda: |-
            wifi::global_wifi_component->forget();

switch:
  - platform: restart
    name: "${friendly_name} Reiniciar (switch)"
