# alarmas_sistema.yaml
# Paquete de sistema de alarmas para ESPHome Professional Packages

globals:
  # Nivel de gravedad global (0: Nada, 1: Leve, 2: Moderado, 3: Grave)
  - id: global_gravedad_alarma
    type: int
    restore_value: no
    initial_value: '0'
  
  # Texto que acumula las alarmas activas
  - id: global_texto_alarmas
    type: std::string
    restore_value: no
    initial_value: '""'

# =============================================================================
# --- PRINCIPAL ---
# =============================================================================
binary_sensor:
  - platform: status
    name: "${friendly_name} Estado HA"
    id: status_ha

  - platform: template
    name: "${friendly_name} Modo sin conexión"
    id: modo_sin_conexion
    device_class: connectivity
    lambda: "return !id(estado_wifi_activo);"

  - platform: template
    name: "${friendly_name} Modo AP"
    id: modo_ap
    device_class: connectivity
    lambda: "return id(estado_ap_activo);"

  - platform: template
    name: "${friendly_name} API conectada"
    id: api_conectada
    device_class: connectivity
    lambda: "return id(estado_api_activa);"

text_sensor:
  - platform: template
    name: "${friendly_name} Estado conexión"
    id: estado_conexion
    update_interval: 15s
    lambda: |-
      if (id(estado_ap_activo)) return {"Modo AP"};
      if (!id(estado_wifi_activo)) return {"Sin conexión"};
      if (!id(estado_api_activa)) return {"No API"};
      return {"Conectado"};


# =============================================================================
# --- SISTEMA ---
# =============================================================================
sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    id: uptime_s
    unit_of_measurement: "s"
    accuracy_decimals: 0
    entity_category: "diagnostic"

  - platform: internal_temperature
    name: "${friendly_name} Temperatura Interna"
    id: internal_temp
    update_interval: 60s
    entity_category: "diagnostic"

text_sensor:
  - platform: version
    name: "${friendly_name} Versión ESPHome"
    hide_timestamp: true
    entity_category: "diagnostic"

  - platform: debug
    reset_reason:
      name: "${friendly_name} Motivo último reinicio"
      entity_category: "diagnostic"

  - platform: template
    name: "${friendly_name} ESPHome Project Version"
    id: esphome_project_version_text_short
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 60s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION };

  - platform: template
    name: "${friendly_name} ESPHome Project Version Detailed"
    id: esphome_project_version_text_detailed
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 60s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION " " + App.get_compilation_time() };

  - platform: template
    name: "${friendly_name} ESPHome Project Name"
    id: esphome_project_name
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 60s
    lambda: |-
      return { ESPHOME_PROJECT_NAME };


# =============================================================================
# --- WIFI ---
# =============================================================================
sensor:
  # Intensidad de señal WiFi (RSSI Brutal)
  - platform: wifi_signal
    name: "${friendly_name} Señal WiFi (dBm)"
    id: wifi_rssi
    update_interval: 60s
    entity_category: "diagnostic"
    on_value_range:
      - below: -78.0
        then:
          - logger.log: "Advertencia: La señal WiFi ha caído por debajo de -78 dBm"

  # Intensidad de señal WiFi en Porcentaje (%)
  - platform: copy
    source_id: wifi_rssi
    name: "${friendly_name} Señal WiFi (%)"
    id: wifi_signal_percent
    unit_of_measurement: "%"
    accuracy_decimals: 0
    entity_category: "diagnostic"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    on_value_range:
      - below: 30.0
        then:
          - logger.log: "Advertencia: La señal WiFi ha caído por debajo del 30%"

text_sensor:
  # Info WiFi
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP actual"
      entity_category: "diagnostic"
    ssid:
      name: "${friendly_name} AP SSID"
      entity_category: "diagnostic"
    bssid:
      name: "${friendly_name} MAC del AP"
      entity_category: "diagnostic"
    mac_address:
      name: "${friendly_name} MAC"
      entity_category: "diagnostic"

text_sensor:
  # Sensor de texto para ver fácilmente el estado (Nada, Leve, Moderado, Grave) en HA
  - platform: template
    name: "Estado de Gravedad"
    id: sensor_gravedad_texto
    icon: "mdi:alert"
    update_interval: never

  # Info WiFi
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP actual"
    ssid:
      name: "${friendly_name} AP SSID conectado"
    bssid:
      name: "${friendly_name} MAC del AP"
    mac_address:
      name: "${friendly_name} MAC"

  - platform: template
    name: "${friendly_name} Estado conexión"
    id: estado_conexion
    update_interval: 15s
    lambda: |-
      if (id(estado_ap_activo)) return {"Modo AP"};
      if (!id(estado_wifi_activo)) return {"Sin conexión"};
      if (!id(estado_api_activa)) return {"No API"};
      return {"Conectado"};

  # Motor principal: Se ejecuta cada 10s, evalúa las condiciones, concatena textos y actualiza la gravedad.
  - platform: template
    name: "Alarmas Activas"
    id: sensor_texto_alarmas
    icon: "mdi:alert-circle"
    update_interval: 10s
    lambda: |-
      std::string alarmas = "";
      int gravedad_max = 0;

      // ==========================================
      // 1. EVALUACIÓN DE ALARMAS Y SENSORES
      // ==========================================
      
      // Ejemplo 1: Alarma por temperatura (Descomentar y ajustar el ID cuando aplique)
      /*
      if (id(sensor_temperatura).has_state()) {
        if (id(sensor_temperatura).state > 65.0) {
          alarmas += "Temp Alta, ";
          if (gravedad_max < 3) gravedad_max = 3; // Grave
        } else if (id(sensor_temperatura).state > 55.0) {
          alarmas += "Temp Elevada, ";
          if (gravedad_max < 2) gravedad_max = 2; // Moderado
        }
      }
      */

      // Ejemplo 2: Señal WiFi
      /*
      if (id(sensor_wifi_signal).has_state()) {
        if (id(sensor_wifi_signal).state < -85.0) {
          alarmas += "WiFi Crítico, ";
          if (gravedad_max < 2) gravedad_max = 2; // Moderado
        } else if (id(sensor_wifi_signal).state < -75.0) {
          alarmas += "WiFi Bajo, ";
          if (gravedad_max < 1) gravedad_max = 1; // Leve
        }
      }
      */

      // ==========================================
      // 2. PROCESAMIENTO FORMATO DE TEXTO
      // ==========================================
      if (alarmas == "") {
        alarmas = "Ninguna";
        gravedad_max = 0;
      } else {
        // Eliminar la coma extra y el espacio al final (", ")
        alarmas = alarmas.substr(0, alarmas.length() - 2);
      }

      // ==========================================
      // 3. ACTUALIZACIÓN ESTADOS HA Y NOTIFICACIONES
      // ==========================================
      // Solo actuar si el nivel de gravedad cambia (evita spam)
      if (id(global_gravedad_alarma) != gravedad_max) {
        id(global_gravedad_alarma) = gravedad_max;
        
        // Publicar el número en HA
        id(sensor_nivel_gravedad).publish_state(gravedad_max);
        
        // Publicar el texto amigable en HA
        std::string texto_gravedad;
        switch(gravedad_max) {
          case 0: texto_gravedad = "Nada"; break;
          case 1: texto_gravedad = "Leve"; break;
          case 2: texto_gravedad = "Moderado"; break;
          case 3: texto_gravedad = "Grave"; break;
          default: texto_gravedad = "Desconocido"; break;
        }
        id(sensor_gravedad_texto).publish_state(texto_gravedad);
        
        // Log / Notificación si es Moderado(2) o Grave(3)
        if (gravedad_max >= 2) {
          ESP_LOGW("alarmas", "Nivel crítico alcanzado: %s. Motivos: %s", texto_gravedad.c_str(), alarmas.c_str());
          // NOTA: Acá es donde puedes disparar un script o hacer un HA service call
          // id(script_alerta_sonora).execute();
        } else if (gravedad_max == 0) {
          ESP_LOGI("alarmas", "El sistema ha regresado a la normalidad.");
        }
      }

      // Guardar el log interno y publicar en el sensor de texto en HA
      id(global_texto_alarmas) = alarmas;
      return alarmas;
